//  ChickenTender-Backend/testData.js

export const jsonData = {
  businesses: [
    {
      id: "ysqgdbSrezXgVwER2kQWKA",
      alias: "julianas-brooklyn-3",
      name: "Juliana's",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/od36nFW220aMFAnNP00ocw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/julianas-brooklyn-3?adjust_creative=f-fNgr8vUIPZ8f3S91hCtQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=f-fNgr8vUIPZ8f3S91hCtQ",
      review_count: 2711,
      categories: [
        {
          alias: "pizza",
          title: "Pizza",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 40.70274718768062,
        longitude: -73.99343490196397,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "19 Old Fulton St",
        address2: "",
        address3: "",
        city: "Brooklyn",
        zip_code: "11201",
        country: "US",
        state: "NY",
        display_address: ["19 Old Fulton St", "Brooklyn, NY 11201"],
      },
      phone: "+17185966700",
      display_phone: "(718) 596-6700",
      distance: 308.56984360837544,
    },
    {
      id: "q11TljTQd33XCWlVoPyRqg",
      alias: "the-osprey-brooklyn",
      name: "The Osprey",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/FDZnyI1ncxyz6vtMv1_7ZA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/the-osprey-brooklyn?adjust_creative=f-fNgr8vUIPZ8f3S91hCtQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=f-fNgr8vUIPZ8f3S91hCtQ",
      review_count: 333,
      categories: [
        {
          alias: "australian",
          title: "Australian",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 40.702241,
        longitude: -73.995539,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "60 Furman St",
        address2: "",
        address3: null,
        city: "Brooklyn",
        zip_code: "11201",
        country: "US",
        state: "NY",
        display_address: ["60 Furman St", "Brooklyn, NY 11201"],
      },
      phone: "+13476962504",
      display_phone: "(347) 696-2504",
      distance: 367.7475436977597,
    },
    {
      id: "MGd6HFEq1ALD58XWNviSXw",
      alias: "time-out-market-new-york-brooklyn",
      name: "Time Out Market New York",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/i6bEoMOoX4cRqgvic8eg6w/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/time-out-market-new-york-brooklyn?adjust_creative=f-fNgr8vUIPZ8f3S91hCtQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=f-fNgr8vUIPZ8f3S91hCtQ",
      review_count: 533,
      categories: [
        {
          alias: "food_court",
          title: "Food Court",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 40.70342863348067,
        longitude: -73.99214637055226,
      },
      transactions: [],
      price: "$$",
      location: {
        address1: "55 Water St",
        address2: "",
        address3: "",
        city: "Brooklyn",
        zip_code: "11201",
        country: "US",
        state: "NY",
        display_address: ["55 Water St", "Brooklyn, NY 11201"],
      },
      phone: "+19178104855",
      display_phone: "(917) 810-4855",
      distance: 288.11900780114274,
    },
    {
      id: "0CjK3esfpFcxIopebzjFxA",
      alias: "joes-shanghai-new-york-2",
      name: "Joe's Shanghai",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/gkp9bzPqrcaWIvgOJbatQw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/joes-shanghai-new-york-2?adjust_creative=f-fNgr8vUIPZ8f3S91hCtQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=f-fNgr8vUIPZ8f3S91hCtQ",
      review_count: 7255,
      categories: [
        {
          alias: "shanghainese",
          title: "Shanghainese",
        },
        {
          alias: "seafood",
          title: "Seafood",
        },
        {
          alias: "noodles",
          title: "Noodles",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 40.7156608,
        longitude: -73.9967012,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "46 Bowery St",
        address2: "",
        address3: "",
        city: "New York",
        zip_code: "10013",
        country: "US",
        state: "NY",
        display_address: ["46 Bowery St", "New York, NY 10013"],
      },
      phone: "+12122338888",
      display_phone: "(212) 233-8888",
      distance: 1153.9482385806896,
    },
    {
      id: "nHMDOIX32dGbfpuNUwsLNQ",
      alias: "almar-brooklyn-2",
      name: "AlMar",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/T55OZs46PGolthDw3ezdCA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/almar-brooklyn-2?adjust_creative=f-fNgr8vUIPZ8f3S91hCtQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=f-fNgr8vUIPZ8f3S91hCtQ",
      review_count: 496,
      categories: [
        {
          alias: "italian",
          title: "Italian",
        },
        {
          alias: "breakfast_brunch",
          title: "Breakfast & Brunch",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 40.702662,
        longitude: -73.989177,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "111 Front St",
        address2: "",
        address3: "",
        city: "Brooklyn",
        zip_code: "11201",
        country: "US",
        state: "NY",
        display_address: ["111 Front St", "Brooklyn, NY 11201"],
      },
      phone: "+17188555288",
      display_phone: "(718) 855-5288",
      distance: 530.8013177444826,
    },
    {
      id: "5CuYWr0-cE01HxlBu5Ka6g",
      alias: "carne-mare-new-york-5",
      name: "Carne Mare",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/fwpce8K4gCL77gy8aydfnQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/carne-mare-new-york-5?adjust_creative=f-fNgr8vUIPZ8f3S91hCtQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=f-fNgr8vUIPZ8f3S91hCtQ",
      review_count: 243,
      categories: [
        {
          alias: "steak",
          title: "Steakhouses",
        },
        {
          alias: "italian",
          title: "Italian",
        },
        {
          alias: "seafood",
          title: "Seafood",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 40.70568649199326,
        longitude: -74.00218961453646,
      },
      transactions: ["delivery"],
      location: {
        address1: "89 South St",
        address2: "",
        address3: "Pier 17",
        city: "New York",
        zip_code: "10038",
        country: "US",
        state: "NY",
        display_address: ["89 South St", "Pier 17", "New York, NY 10038"],
      },
      phone: "+12122804600",
      display_phone: "(212) 280-4600",
      distance: 666.1578018948308,
    },
    {
      id: "8YWLuLUKj0t_0_Xv06UUtw",
      alias: "yes-apothecary-new-york-4",
      name: "Ye's Apothecary",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/C9kLckBI7NTHBnHV-98qEw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/yes-apothecary-new-york-4?adjust_creative=f-fNgr8vUIPZ8f3S91hCtQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=f-fNgr8vUIPZ8f3S91hCtQ",
      review_count: 422,
      categories: [
        {
          alias: "szechuan",
          title: "Szechuan",
        },
        {
          alias: "speakeasies",
          title: "Speakeasies",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 40.71945,
        longitude: -73.9898,
      },
      transactions: [],
      price: "$$$",
      location: {
        address1: "119 Orchard St",
        address2: null,
        address3: "",
        city: "New York",
        zip_code: "10002",
        country: "US",
        state: "NY",
        display_address: ["119 Orchard St", "New York, NY 10002"],
      },
      phone: "",
      display_phone: "",
      distance: 1602.8275228141238,
    },
    {
      id: "-Gc5sTFxoXM3Tiv_dkSJZg",
      alias: "cecconis-dumbo-brooklyn",
      name: "Cecconi's Dumbo",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/wLkTt8QVE6awOocmAW194A/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/cecconis-dumbo-brooklyn?adjust_creative=f-fNgr8vUIPZ8f3S91hCtQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=f-fNgr8vUIPZ8f3S91hCtQ",
      review_count: 1080,
      categories: [
        {
          alias: "italian",
          title: "Italian",
        },
      ],
      rating: 3.5,
      coordinates: {
        latitude: 40.7033063330116,
        longitude: -73.9916549604523,
      },
      transactions: ["delivery"],
      price: "$$$",
      location: {
        address1: "55 Water St",
        address2: "",
        address3: null,
        city: "Brooklyn",
        zip_code: "11201",
        country: "US",
        state: "NY",
        display_address: ["55 Water St", "Brooklyn, NY 11201"],
      },
      phone: "+17186503900",
      display_phone: "(718) 650-3900",
      distance: 325.5822990331506,
    },
    {
      id: "9I8mZXCkGZBmFh5fYOYorw",
      alias: "em-vietnamese-bistro-brooklyn",
      name: "Em Vietnamese Bistro",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/xEGNtQssJsP4WmLP6p69kg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/em-vietnamese-bistro-brooklyn?adjust_creative=f-fNgr8vUIPZ8f3S91hCtQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=f-fNgr8vUIPZ8f3S91hCtQ",
      review_count: 164,
      categories: [
        {
          alias: "vietnamese",
          title: "Vietnamese",
        },
        {
          alias: "noodles",
          title: "Noodles",
        },
        {
          alias: "sandwiches",
          title: "Sandwiches",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 40.702670064808366,
        longitude: -73.99118578021728,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "57 Front St",
        address2: "",
        address3: null,
        city: "Brooklyn",
        zip_code: "11201",
        country: "US",
        state: "NY",
        display_address: ["57 Front St", "Brooklyn, NY 11201"],
      },
      phone: "+17188757888",
      display_phone: "(718) 875-7888",
      distance: 404.73797588732526,
    },
    {
      id: "SWK0AQ5KTDDCt8AtOhhasg",
      alias: "malibu-farm-new-york-new-york-2",
      name: "Malibu Farm New York",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/CoIm4zQC690JynEdjiQ9rw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/malibu-farm-new-york-new-york-2?adjust_creative=f-fNgr8vUIPZ8f3S91hCtQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=f-fNgr8vUIPZ8f3S91hCtQ",
      review_count: 379,
      categories: [
        {
          alias: "newamerican",
          title: "New American",
        },
        {
          alias: "venues",
          title: "Venues & Event Spaces",
        },
        {
          alias: "beer_and_wine",
          title: "Beer, Wine & Spirits",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 40.705644,
        longitude: -74.00188,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "89 South St",
        address2: "",
        address3: null,
        city: "New York",
        zip_code: "10038",
        country: "US",
        state: "NY",
        display_address: ["89 South St", "New York, NY 10038"],
      },
      phone: "+12122653030",
      display_phone: "(212) 265-3030",
      distance: 619.5268971577544,
    },
    {
      id: "WG639VkTjmK5dzydd1BBJA",
      alias: "rubirosa-new-york-2",
      name: "Rubirosa",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/l0Phrnhhj78RFiDhLIOUyQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/rubirosa-new-york-2?adjust_creative=f-fNgr8vUIPZ8f3S91hCtQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=f-fNgr8vUIPZ8f3S91hCtQ",
      review_count: 3197,
      categories: [
        {
          alias: "italian",
          title: "Italian",
        },
        {
          alias: "pizza",
          title: "Pizza",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 40.722766,
        longitude: -73.996233,
      },
      transactions: ["pickup"],
      price: "$$",
      location: {
        address1: "235 Mulberry St",
        address2: "",
        address3: "",
        city: "New York",
        zip_code: "10012",
        country: "US",
        state: "NY",
        display_address: ["235 Mulberry St", "New York, NY 10012"],
      },
      phone: "+12129650500",
      display_phone: "(212) 965-0500",
      distance: 1932.9467701334759,
    },
    {
      id: "-2UtjTxrt1Xzd-HPsLJ7mA",
      alias: "butler-brooklyn-2",
      name: "Butler",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/bdMNkvxL7UpST2PuDCjvXw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/butler-brooklyn-2?adjust_creative=f-fNgr8vUIPZ8f3S91hCtQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=f-fNgr8vUIPZ8f3S91hCtQ",
      review_count: 199,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
        {
          alias: "cafes",
          title: "Cafes",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 40.7032670673495,
        longitude: -73.9922419276899,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "40 Water St",
        address2: "",
        address3: null,
        city: "Brooklyn",
        zip_code: "11201",
        country: "US",
        state: "NY",
        display_address: ["40 Water St", "Brooklyn, NY 11201"],
      },
      phone: "",
      display_phone: "",
      distance: 299.48141504845114,
    },
    {
      id: "Qi7pmy2BuR5Oz2ouXa2u4A",
      alias: "the-frenchmans-dough-new-york",
      name: "The Frenchman's Dough",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/O7EF4lqRagl2BRcPFAClZA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/the-frenchmans-dough-new-york?adjust_creative=f-fNgr8vUIPZ8f3S91hCtQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=f-fNgr8vUIPZ8f3S91hCtQ",
      review_count: 42,
      categories: [
        {
          alias: "italian",
          title: "Italian",
        },
        {
          alias: "pizza",
          title: "Pizza",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 40.706116183284095,
        longitude: -74.00233246386051,
      },
      transactions: [],
      location: {
        address1: "96 South St",
        address2: "",
        address3: null,
        city: "New York",
        zip_code: "10038",
        country: "US",
        state: "NY",
        display_address: ["96 South St", "New York, NY 10038"],
      },
      phone: "+16468686000",
      display_phone: "(646) 868-6000",
      distance: 681.7538405031452,
    },
    {
      id: "CqtT8rPaSmrRClUBbqsCFA",
      alias: "seamore-s-dumbo-brooklyn-3",
      name: "Seamore’s Dumbo",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/umIclGRktw-NX2nW_hBlvA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/seamore-s-dumbo-brooklyn-3?adjust_creative=f-fNgr8vUIPZ8f3S91hCtQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=f-fNgr8vUIPZ8f3S91hCtQ",
      review_count: 209,
      categories: [
        {
          alias: "seafood",
          title: "Seafood",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
        {
          alias: "breakfast_brunch",
          title: "Breakfast & Brunch",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 40.703086,
        longitude: -73.991307,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "66 Water St",
        address2: "",
        address3: null,
        city: "Brooklyn",
        zip_code: "11201",
        country: "US",
        state: "NY",
        display_address: ["66 Water St", "Brooklyn, NY 11201"],
      },
      phone: "+17186636550",
      display_phone: "(718) 663-6550",
      distance: 361.28143291858544,
    },
    {
      id: "hLXe3RVRK39VUSPdvBjFEA",
      alias: "kalye-new-york",
      name: "Kalye",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/7iAlnjzSOebk2p0w2LB3Vg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/kalye-new-york?adjust_creative=f-fNgr8vUIPZ8f3S91hCtQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=f-fNgr8vUIPZ8f3S91hCtQ",
      review_count: 111,
      categories: [
        {
          alias: "filipino",
          title: "Filipino",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 40.7179,
        longitude: -73.98999,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "251 Broome St",
        address2: "",
        address3: null,
        city: "New York",
        zip_code: "10002",
        country: "US",
        state: "NY",
        display_address: ["251 Broome St", "New York, NY 10002"],
      },
      phone: "+16464227267",
      display_phone: "(646) 422-7267",
      distance: 1432.6644474557947,
    },
    {
      id: "JQDVA6_dRpg7RlxlZmJr0w",
      alias: "chama-mama-brooklyn-heights-brooklyn",
      name: "Chama Mama - Brooklyn Heights",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/JWKHB0MOqvMqXOHjlUzUrA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/chama-mama-brooklyn-heights-brooklyn?adjust_creative=f-fNgr8vUIPZ8f3S91hCtQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=f-fNgr8vUIPZ8f3S91hCtQ",
      review_count: 14,
      categories: [
        {
          alias: "georgian",
          title: "Georgian",
        },
        {
          alias: "wine_bars",
          title: "Wine Bars",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 40.69498,
        longitude: -73.9945,
      },
      transactions: ["pickup", "delivery"],
      location: {
        address1: "121 Montague St",
        address2: "",
        address3: null,
        city: "Brooklyn",
        zip_code: "11201",
        country: "US",
        state: "NY",
        display_address: ["121 Montague St", "Brooklyn, NY 11201"],
      },
      phone: "+13476892725",
      display_phone: "(347) 689-2725",
      distance: 1161.3471706765317,
    },
    {
      id: "hNFe8WhCibrqT4sFcZmAgw",
      alias: "kong-sihk-tong-港食堂-new-york",
      name: "Kong Sihk Tong 港食堂",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/S9pXbhbanRRNjDg3DffhBQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/kong-sihk-tong-%E6%B8%AF%E9%A3%9F%E5%A0%82-new-york?adjust_creative=f-fNgr8vUIPZ8f3S91hCtQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=f-fNgr8vUIPZ8f3S91hCtQ",
      review_count: 779,
      categories: [
        {
          alias: "chinese",
          title: "Chinese",
        },
        {
          alias: "hkcafe",
          title: "Hong Kong Style Cafe",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 40.715433714742154,
        longitude: -73.9981186386701,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "65 Bayard St",
        address2: "",
        address3: null,
        city: "New York",
        zip_code: "10013",
        country: "US",
        state: "NY",
        display_address: ["65 Bayard St", "New York, NY 10013"],
      },
      phone: "+16468506140",
      display_phone: "(646) 850-6140",
      distance: 1156.5626748255393,
    },
    {
      id: "56qlj1cYlqNzmG0xllGg-w",
      alias: "westville-brooklyn",
      name: "Westville",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/ahbPGgyPtE8qvu_UzRADVQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/westville-brooklyn?adjust_creative=f-fNgr8vUIPZ8f3S91hCtQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=f-fNgr8vUIPZ8f3S91hCtQ",
      review_count: 411,
      categories: [
        {
          alias: "mediterranean",
          title: "Mediterranean",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 40.70208865020039,
        longitude: -73.9894541379247,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "81 Washington St",
        address2: "",
        address3: null,
        city: "Brooklyn",
        zip_code: "11201",
        country: "US",
        state: "NY",
        display_address: ["81 Washington St", "Brooklyn, NY 11201"],
      },
      phone: "+17186185699",
      display_phone: "(718) 618-5699",
      distance: 552.8717360375787,
    },
    {
      id: "m4lJL1hpJCkfB_fXsj8iQQ",
      alias: "the-rogue-panda-brooklyn",
      name: "The Rogue Panda",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/fMI8pyL0NOt7oE3s9-g_ew/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/the-rogue-panda-brooklyn?adjust_creative=f-fNgr8vUIPZ8f3S91hCtQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=f-fNgr8vUIPZ8f3S91hCtQ",
      review_count: 62,
      categories: [
        {
          alias: "chinese",
          title: "Chinese",
        },
        {
          alias: "vegan",
          title: "Vegan",
        },
        {
          alias: "vegetarian",
          title: "Vegetarian",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 40.703418788303445,
        longitude: -73.9923495,
      },
      transactions: [],
      location: {
        address1: "55 Water St",
        address2: "Ste 5",
        address3: "",
        city: "Brooklyn",
        zip_code: "11201",
        country: "US",
        state: "NY",
        display_address: ["55 Water St", "Ste 5", "Brooklyn, NY 11201"],
      },
      phone: "+13055045191",
      display_phone: "(305) 504-5191",
      distance: 278.56859883440774,
    },
    {
      id: "4aF0F8w7yXX9o5_QFky_ig",
      alias: "celestine-brooklyn",
      name: "Celestine",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/p98BTWB9IIb4RQyDQw13ZQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/celestine-brooklyn?adjust_creative=f-fNgr8vUIPZ8f3S91hCtQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=f-fNgr8vUIPZ8f3S91hCtQ",
      review_count: 297,
      categories: [
        {
          alias: "mediterranean",
          title: "Mediterranean",
        },
        {
          alias: "bars",
          title: "Bars",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 40.704676,
        longitude: -73.987975,
      },
      transactions: ["delivery"],
      price: "$$$",
      location: {
        address1: "1 John St",
        address2: "",
        address3: null,
        city: "Brooklyn",
        zip_code: "11201",
        country: "US",
        state: "NY",
        display_address: ["1 John St", "Brooklyn, NY 11201"],
      },
      phone: "+17185225356",
      display_phone: "(718) 522-5356",
      distance: 539.4069533813018,
    },
  ],
  total: 4700,
  region: {
    center: {
      longitude: -73.99429321289062,
      latitude: 40.70544486444615,
    },
  },
};
